SRC_NAME=core/main.c\
		 core/setup.c\
		 core/free.c\
		 core/error.c\
		 \
		 mlx/init_mlx.c\
		 mlx/events.c\
		 mlx/render.c\
		 mlx/tools.c\
		 \
		 opencl/init_opencl.c\
		 opencl/launch_kernels.c
