SRC_NAME=core/main.c\
		 core/setup.c\
		 core/free.c\
		 core/error.c\
		 \
		 mlx/init_mlx.c\
		 mlx/events.c\
		 mlx/render.c\
		 mlx/tools.c\
		 \
		 opencl/init_opencl.c\
		 opencl/launch_kernels.c\
		 opencl/buffers.c\
		 \
		 scene_parser/scene_parser.c\
		 scene_parser/get_variables.c\
		 scene_parser/var_parsing_fts.c\
		 scene_parser/addobj.c\
		 scene_parser/add_sphere.c\
		 scene_parser/add_polygon.c\
		 scene_parser/addlight.c
