#ifndef ERRORS_H
# define ERRORS_H



enum	e_errors
{
	ERROR_MLX_LAUNCH,
	ERROR_KERNEL_MAPPING_FAILED,
	ERROR_PROGRAM_CREATION_FAILED,
	ERROR_KERNEL_BUILD_FAILED,
	ERROR_KERNEL_CREATION_FAILED,
	ERROR_NO_CL_DEVICE,
	ERROR_CL_CONTEXT_CREATION_FAILED,
	ERROR_CL_CMD_QUEUE_CREATION_FAILED,
	ERROR_NO_VAR_SPECIFIED_FOR_SET_CMD,
	ERROR_MALLOC_FAILED,
	ERROR_SCENE_FILE_MEMORY_MAPPING_FAILED,
	ERROR_INVALID_SCENE_FILE_PATH,
	ERROR_VARIABLE_NOT_FOUND,
	ERROR_INVALID_VECTOR_SYNTAX,
	ERROR_MISSING_COMPONENT_IN_VECTOR,
	ERROR_INVALID_WINDOW_DIMENSION,
	ERROR_INVALID_FOV,
	ERROR_INVALID_BRIGHTNESS,
	ERROR_INVALID_SET_CMD_SYNTAX,
	ERROR_NO_TYPE_FOR_ADDOBJ_CMD,
	ERROR_INVALID_TYPE_FOR_ADDOBJ_CMD,
	ERROR_COLOR_VALUE_OUT_OF_RANGE,
	ERROR_NEGATIVE_RADIUS_VALUE,
	ERROR_INVALID_CONE_HEIGHT_VALUE,
	ERROR_NO_SCENE,
	ERROR_ARG_NOT_FOUND,
	ERROR_INVALID_SPECULAR_EXPONENT_VALUE,
	ERROR_INVALID_OPACITY_VALUE,
	ERROR_INVALID_CHAR_IN_MTL_NAME,
	ERROR_MTL_NAME_NOT_FOUND,
	ERROR_MTL_NAME_TOO_LONG,
	ERROR_MATERIAL_NOT_FOUND,
	ERROR_MAX
};

void	rt_error(int exit_code);

#endif
